---
#
- apt:
    name: mariadb-server

- get_url:
    url: "{{ mariadb_entrypoint_url }}"
    dest: "{{ mariadb_home }}/entrypoint.sh"
    mode: "u+x"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
  become_user: "{{ mariadb_user }}"

- name: install python module
  pip:
    name: MySQL-python
